spring:
  datasource:
    url: jdbc:mysql://localhost:3307/bank
    username: root
    password: root

  jpa:
    hibernate:
      ddl-auto: update # 테이블 자동 생성 및 업데이트
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always