global:
  scrape_interval: 5s
  evaluation_interval: 5s

# 기존 scrape_configs 유지
scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'spring-actuator'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:8080'] # 로컬 호스트에서 앱 실행할 경우

  - job_name: 'k6'
    metrics_path: '/metrics'
    scrape_interval: 5s
    static_configs:
      - targets: ['k6:6565']